import turtle
h = turtle.Turtle()
h.up()
h.backward(290)
def house():
  number = int(input("# of Houses: "))
  i = 0
  while i < number:
    length = int(input("Length: "))
    height = int(input("Height: "))
    dh = int(input("Door Height: "))
    dw = int(input("Door Width: "))
    color = input("Color: ")
    distance = (length / 2) - (dw /2)  
    h.down()
    h.color(color)
    h.forward(length)
    h.left(90)
    h.forward(height)
    h.left(30)
    h.forward(length)
    h.left(120)
    h.forward(length)
    h.left(120)
    h.forward(length)
    h.left(180)
    h.forward(length)
    h.left(90)
    h.forward(height)
    h.left(90)
    h.forward(distance)
    h.left(90)
    h.forward(dh)
    h.right(90)
    h.forward(dw)
    h.right(90)
    h.forward(dh)
    h.left(90)
    h.up()
    a = distance + 20
    h.forward(a)
    i += 1
house()